// AUTO-GENERATED by scripts/gen-build-info.mjs at prebuild.
// Do not edit by hand — value reflects the most recent build/deploy.
export const BUILD_STAMP = '20260525-2146';
export const BUILD_ISO = '2026-05-26T04:46:52.652Z';
